[[constraint]]
  name = "firebase.google.com/go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/SermoDigital/jose"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  name = "google.golang.org/appengine"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true
